FROM debian:stretch-slim

RUN apt-get update && \
	apt-get install -y \
	autoconf \
	automake \
	bc \
	bison \
	build-essential \
	curl \
	dpkg-dev \
	fakeroot \
	file \
	flex \
	gawk \
	git \
	libgmp-dev \
	libmpc-dev \
	libmpfr-dev \
	libtool \
	texinfo \
	cpio \
	wget && \
	rm -rf /var/lib/apt/lists/*

ENV PATH="/opt/cross/bin:${PATH}"

COPY ci/octeon-toolchain.sh /build_toolchain.sh

RUN chmod +x /build_toolchain.sh && /build_toolchain.sh

ENV CROSSCOMPILE="mips64-octeon-linux-"
