FROM debian:stretch-slim

# Add mipsel support and install build tools
RUN dpkg --add-architecture mipsel && \
	apt-get update && \
	apt-get -y install \
	build-essential \
	curl \
	dpkg-cross \
	g++-mipsel-linux-gnu \
	git \
	bc \
	bison \
	flex \
	cpio && \
	rm -rf /var/lib/apt/lists/*

ENV CROSSCOMPILE="mipsel-linux-gnu-"
