FROM debian:trixie-slim

RUN apt-get update && \
	apt-get install -y \
	autoconf \
	automake \
	bc \
	bison \
	build-essential \
	curl \
	dpkg-dev \
	fakeroot \
	file \
	flex \
	gawk \
	git \
	libgmp-dev \
	libmpc-dev \
	libmpfr-dev \
	libtool \
	texinfo \
	cpio \
	wget \
	jq && \
	rm -rf /var/lib/apt/lists/*

ARG BINUTILS_VER=2.29.1
ARG GCC_VER=4.8.5
ARG GMP_VER=6.3.0
ARG ISL_VER=0.18
ARG MPC_VER=1.4.0
ARG MPFR_VER=4.2.2

ARG TARGET=mipsel-mtk-linux

ENV PATH="/opt/cross/bin:${PATH}"

COPY ci/mtk-toolchain.sh /build_toolchain.sh

RUN chmod +x /build_toolchain.sh && /build_toolchain.sh

ENV CROSSCOMPILE="mipsel-mtk-linux-"
