FROM alpine:3.11

# Install build dependencies
RUN apk add --no-cache \
	--update-cache \
	autoconf \
	automake \
	bc \
	bison \
	build-base \
	coreutils \
	curl \
	file \
	flex \
	gawk \
	git \
	gmp-dev \
	libtool \
	linux-headers \
	mpc1-dev \
	mpfr-dev \
	shadow \
	su-exec \
	texinfo \
	wget \
	kmod \
	gnupg \
	jq


# Let any user elevate to root
RUN chmod +s /sbin/su-exec

# Fix /tmp permissions
RUN chmod 777 /tmp

ENV BINUTILS_VER=2.32
ENV GCC_VER=8.3.0
ENV GMP_VER=6.1.2
ENV ISL_VER=0.19
ENV KERNEL_VER=4.19.47
ENV MPC_VER=1.1.0
ENV MPFR_VER=4.0.2
ENV MUSL_VER=1.1.22

ENV PATH="/opt/cross/bin:${PATH}"

ENV TARGET="$ARCH-linux-musl"

COPY ci/octeon-toolchain.sh /build_toolchain.sh

RUN chmod +x /build_toolchain.sh && /build_toolchain.sh
