name: Build docker build environments

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:

    runs-on: ubuntu-24.04

    strategy:
        matrix:
          tag: [mips, mipsel, mtk, octeon]
          type: [kernel, tools]
          exclude:
            - tag: mips
              type: kernel
            - tag: mtk
              type: tools
            - tag: octeon
              type: tools
    env:
      IMAGE: ghcr.io/${{ github.repository }}/ubnt-build:${{ matrix.tag }}-${{ matrix.type }}

    steps:
      - uses: actions/checkout@v6

      - name: Build kernel environment
        if: ${{ matrix.type == 'kernel' }}
        run: docker build --pull -t "$(echo $IMAGE | tr '[:upper:]' '[:lower:]')" -f ci/DOCKERFILE-${{ matrix.tag }} .

      - name: Build tools environment
        if: ${{ matrix.type == 'tools' }}
        run: docker build --pull --build-arg ARCH=${{ matrix.tag }} -t "$(echo $IMAGE | tr '[:upper:]' '[:lower:]')" -f ci/DOCKERFILE-tools .

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GitHub Container Registry
        run: docker push "$(echo $IMAGE | tr '[:upper:]' '[:lower:]')"
